TAG_BLOCKLIST = [
    ["ol", {"class": "references"}],
    [None, {"class": "reference"}],
    ["link"],
    ["style"],
    ["img"],
    ["aside"],
    ["table"],
    ["br"],
    ["span", {"class": "mw-ext-cite-error"}],
    ["div", {"class": "thumbinner"}],
    ["div", {"class": "gallerytext"}],
    ["div", {"class": "archwiki-template-meta-related-articles-start"}],
    ["div", {"class": "tright"}],
    ["div", {"class": "plainlist"}],
    ["div", {"class": "gametabs"}],
    [None, {"class": "noprint"}],
    ["span", {"id": "w4g_rb_area-1"}],
    ["p", {"class": "caption"}],
]


IMAGE_BLOCKLIST = [
    "Gtk-redo-ltr.svg",
    "48ef4db2ad.png",
    "Pen_and_book.jpg",
    "Lurkomoring.png",
    "WALL_OF_TEXT.jpg",
    "Attention32.png",
    "AngryMonkey.png",
    "Lentaru.png",
    "Refresh.png",
    "Barbed_wire_new_flip.png",
    "APNGball.png",
    "Important.png",
    "Chaos_star_transp.png",
    "Krasiviy_petushok.jpg",
    "Hypnotoad_1.gif",
    "ZOG1.jpg",
    "Brick_one.jpg",
    "Rav.jpg",
    "Матановая_капча1.png",
    "Drama.png",
    "Notcrap_small.png",
    "Tomat.jpg",
    "Trash.PNG",
    "Raksmall.gif",
    "A.S._Pushkin.jpg",
    "Shkolota.jpg",
    "520px-Diamond-caution.svg.png",
    "Miseri.png",
    "Banhammer.png",
    "Dyhota.png",
    "Боевой_треножник.jpg",
    "Huy.png",
    "Protect.svg",
    "1259141754733.jpg",
    "Blood_jar.png",
    "Big_lie.png",
    "Warning_1.png",
    "Tema_sm.jpg",
    "Boroda.jpeg",
    "Post-negrov-small.jpg",
    "Advicedog.jpg",
    "Renamed.png",
    "Renamed_self.png",
    "0667d021c975.jpg",
    "Nihuya-small.png",
    "Tema_sm_blind.jpg",
    "Not_found_2.svg",
    "GN_small2.png",
    "Kash.png",
    "UnLurkomoring.PNG",
    "Hate_small.png",
    "Nohate.jpg",
    "RedHate.png",
    "Mergearticles.png",
    "Cut.png",
    "19_md_house.jpg",
    "Linkota.jpg",
    "Нет.png",
    "Dont_feed_the_troll_small.png",
    "Slowpoke.png",
    "Smile.svg",
    "St.jpg",
    "Petrosyan.png",
    "Wrar64.png",
    "Кунсткамера.png",
    "Capsula.png",
    "Politota.png",
    "10к.gif",
    "Kapitan_ochevidnost'.jpg",
    "Facepalm_kyon_sq.jpg",
    "Eri-x-Yakumo.jpg",
    "Свиборг.png",
    "Butthurt.png",
    "Aalien_pony.png",
    "Uvaga.gif",
    "Ae_logo_smallfile.png",
    "Nestle.png",
    "Emblem-important.svg",
    "Stroke.png",
    "Necronomicon.png",
    "Ug.png",
    "Spoiler_alert.jpg",
    "Tuesday,_2_February.png",
    "Recycle.png",
    "Ammonite,_Quenstedtoceras_paucicostatum.jpg",
    "Dont_drink_1.jpg",
]


DEFAULT_PARAMS = {"format": "json", "action": "query", "formatversion": 2}


WGR_FLAG = (
    "https://upload.wikimedia.org/wikipedia/commons/thumb"
    + "/8/85/Flag_of_Belarus.svg/1000px-Flag_of_Belarus.svg.png"
)

WRW_FLAG = (
    "https://upload.wikimedia.org/wikipedia/commons/thumb"
    + "/5/50/Flag_of_Belarus_%281918%2C_1991%E2%80%931995%29.svg"
    + "/1000px-Flag_of_Belarus_%281918%2C_1991%E2%80%931995%29.svg.png"
)
